# Name of workflow
name: PR workflow for shell scripts

# Trigger workflow on pull requests only
on: pull_request

# Configure the jobs that the workflow must complete
jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
    - name: Execute shell script
      run: ./test_script.sh
